export const retos = [
  { id: "1", reto: "tiene que besar con lengua a" },
  { id: "2", reto: "muerdele la nalga a" },
  { id: "3", reto: "escoja una persona para hacer beso de tres con" },
  { id: "4", reto: "hazle un baile a solas a" },
  { id: "5", reto: "5 minutos en el cielo con" },
  { id: "6", reto: "deberas quitarte una prenda mutuamente con" },
  { id: "7", reto: "chupale el dedo gordo del pie a" },
  { id: "8", reto: "dejate besar en el cuello de" },
  { id: "9", reto: "dejate vendar los ojos y seducir solo con el tacto de" },
  { id: "10", reto: "vendale los ojos y seduce solo con el tacto a" },
  { id: "11", reto: "roza tu lengua (solo tu lengua) con la de" },
  { id: "12", reto: "bajale el cierre del pantalon con los dientes a" },
  { id: "13", reto: "muestrale una parte de tu cuerpo que quiera ver" },
  { id: "14", reto: "toma un shot en el ombligo de" },
  { id: "15", reto: "haz lo que te pida" },
  { id: "15", reto: "cantale la cancion que te pida" },
  { id: "16", reto: "deberas nadar desnudo en una piscina con" },
  { id: "17", reto: "vendate los ojos y besa la persona que escoja" },
  { id: "18", reto: "vendale los ojos y ponle una persona para que la bese a" },
  {
    id: "19",
    reto: "deberas elegir una posicion sexual extraña y recreala con",
  },
  {
    id: "20",
    reto: "el publico elige 3 preguntas y tu juega verdad o shot con",
  },
  { id: "21", reto: "dejate quitar 3 prendas de" },
  {
    id: "22",
    reto: "juega 5 veces piedra,papel o tijera (el perdedor toma shot) con",
  },
  { id: "23", reto: "deberas tomar 3 shots con" },
  {
    id: "24",
    reto: "pasale tu ropa interior para que se la ponga en la cabeza a",
  },
  { id: "25", reto: "ponte en la cabeza la ropa interior de" },
  { id: "26", reto: "nalguea 5 veces a" },
  { id: "27", reto: "dejate nalguear 5 veces por" },
  { id: "28", reto: "muestrale tu pack a" },
  { id: "29", reto: "tienes que ver el pack de" },
  { id: "30", reto: "besate durante 2 minutos contabilizados con" },
  { id: "31", reto: "deberas hacer el reto que los demas escojan con" },
  {
    id: "32",
    reto: "deberas mantener tu mano hasta nuevamente tu turno, sin tocar sus genitales, en el extremo la entrepierna de",
  },
  { id: "33", reto: "ponle un reto con otra persona a" },
  { id: "34", reto: "juega 4 intentos de beer pong prenda con" },
  {
    id: "35",
    reto: "deberas sentarte hasta nuevamente tu turno en las piernas de",
  },
  {
    id: "36",
    reto: "deberas cargar en tus piernas hasta nuevamente tu turno a",
  },
  { id: "37", reto: "metele la lengua en la nariz a" },
  { id: "38", reto: "dejate meter la lengua en la nariz de" },
  { id: "39", reto: "deberas recibir un striptease a solas de" },
  { id: "40", reto: "dejate lamer cualquier parte del cuerpo de" },
];
